### ISSUE TITLE
404 Page not found

### ISSUE THREAD

**Issue by connorc170** [razziel89/mealie-addons#10]
Setting this up for the first time - my mealie instance is working properly and is accessible. Copy and pasted the compose template -

```
    mealie-addons:
        image: ghcr.io/razziel89/mealie-addons:latest
        container_name: mealie-addons
        depends_on: [mealie]
        restart: always
        ports:
            - "9926:9000"
        environment:
            # The following environment variables are mandatory.
            MA_LISTEN_INTERFACE: ":9000"
            MA_RETRIEVAL_LIMIT: "5"
            MA_TIMEOUT_SECS: "60"
            MA_STARTUP_GRACE_SECS: "30"
            MEALIE_BASE_URL: "https://mealie.yourdomain.com"
            MEALIE_RETRIEVAL_URL: "http://mealie:9000"
            MEALIE_TOKEN: "/run/secrets/MEALIE_TOKEN"
            GIN_MODE: release
            # The following environment variables are optional.
            PANDOC_FONTS_DIR: .
            PANDOC_FLAGS: |-
                --epub-title-page=false
            MA_IMAGE_ACTION: embed
            MA_HTML_ATTRS_MOD: |
              <img width="15%">
            MA_HTML_ATTRS_RM: |
              <img height="">
            MA_SELF_URL: "http://127.0.0.1:9926"
        secrets:
            - MEALIE_TOKEN

volumes:
    mealie-data:

secrets:
    MEALIE_TOKEN:
        # This is the file containing the token used to access mealie. The path
        # is relative to the location of this file.
        file: mealie_token.txt
```

Obviously changed MEALIE_BASE_URL to the domain I would use to access Mealie. Also tried changing the retrieval URL to the same domain as a troubleshooting step.
Made a mealie_token.txt in the same directory as my docker-compose.yml with my API token from Mealie. Navigating to /run/secrets/MEALIE_TOKEN shows the correct token, generated a new one and recreated the container and it reflected the changed token.
When navigating to <ip of docker host>:9925 I get Mealie with no problems. <ip of docker host>:9926 gives ```404 page not found``` and makes a log in the container ```[GIN] 2025/04/27 - 00:56:14 | 404 |         500ns |     <ip of device> | GET      "/"```
Tried on multiple devices that all have no problems accessing Mealie.
I have to be missing something here. Thanks in advance for any help!
