### ISSUE TITLE
pdf is not working

### ISSUE THREAD

**Issue by FGOD1983** [razziel89/mealie-addons#11]
I managed to get the mealie-addons working, but pdf is not working. It results in a `ERR_INVALID_RESPONSE` while epub and html do work (although it excluded images from the recepies, not sure if that should be in the html/epub that is generated).

**Comment by razziel89** [comment]
Hi @FGOD1983. Thanks for reaching out. How did you set up `mealie-addons`? Are you using the docker image or are you running the binary directly on a computer? In the latter case, some more dependencies might have to be installed. That is why I recommend the docker-based installation, if possible. PDF generation should work out of the box for a docker-based setup.

**Comment by razziel89** [comment]
Regarding image generation: Have you set the environment variable `MA_IMAGE_ACTION`? It needs to be set to have images embedded please see [this part of the readme](https://github.com/razziel89/mealie-addons#environment-variables) for details on all environment variables used by `mealie-addons`.

**Comment by FGOD1983** [comment]
Hey @razziel89. I have used the seperate Docker compose from the example (because docker was complaining about added services when I tried to do it together with mealie in the same compose yaml).

The `MA_IMAGE_ACTION` setting is set to embed as you can see below.

I also noticed that I was unable to reach it over the mealie url eventhough that is set, so I am using the IP with port instead, but that could be a problem with the nginx proxy manager and the fact that it runs on the same server within 2 different docker containers.

below is my yaml file:

```
---
services:
    mealie-addons:
        image: ghcr.io/razziel89/mealie-addons:latest
        container_name: mealie-addons
        restart: always
        ports:
            - "9926:9000"
        environment:
            # The following environment variables are mandatory.
            MA_LISTEN_INTERFACE: ":9000"
            MA_RETRIEVAL_LIMIT: "5"
            MA_TIMEOUT_SECS: "60"
            MA_STARTUP_GRACE_SECS: "30"
            MEALIE_BASE_URL: "MY_MEALIE_URL"
            MEALIE_RETRIEVAL_URL: "MY_MEALIE_URL"
            MEALIE_TOKEN: "/run/secrets/MEALIE_TOKEN"
            GIN_MODE: release
            # The following environment variables are optional.
            PANDOC_FONTS_DIR: .
            PANDOC_FLAGS: |-
                --epub-title-page=false
            MA_IMAGE_ACTION: embed
            MA_HTML_ATTRS_MOD: |
              <img width="15%">
            MA_HTML_ATTRS_RM: |
              <img height="">
            MA_SELF_URL: "MY_MEALIE_URL:9926"
        secrets:
            - MEALIE_TOKEN

secrets:
    MEALIE_TOKEN:
        # This is the file containing the token used to access mealie. The path
        # is relative to the location of this file.
        file: mealie_token.txt
```
