### ISSUE TITLE
Stand-alone Compose File

### ISSUE THREAD

**Issue by diedrichg** [razziel89/mealie-addons#5]
Hello. I'm trying to deploy your addon in Unraid using the Docker Compose plugin. I'm not able to get it up and running because I already have a Mealie image running from the Unraid app store. I'm trying to exclude the mealie portion of your compose file but I'm unsuccessful.

Would you provide a stand-alone compose file example with notes needed to reference a separate docker image, please?

**Comment by razziel89** [comment]
Thanks for your interest and thanks for reaching out! I haven't had access to an Unraid system, which is why I couldn't try out how to get `mealie-addons` running on it next to `mealie`. But I'm sure we can figure out how.

This is a stand-alone compose file based on the combined one from the readme. I've added some comments to the parts of the file that will have to be adjusted. 

```yaml
---
services:
    mealie-addons:
        container_name: mealie-addons
        restart: always
        ports:
            # In this example, mealie-addons will be accessible on port 9926.
            # Adjust this as needed.
            - "9926:9000"
        build:
            args:
               MA_VERSION: "0.1.0"
            context: .
            dockerfile_inline: |
                FROM golang:1.23-bookworm AS builder
                RUN \
                  apt-get update && \
                  DEBIAN_FRONTEND=noninteractive apt-get install -y make git
                WORKDIR /app
                RUN \
                  git clone https://github.com/razziel89/mealie-addons . && \
                  git checkout "$${MA_VERSION}" && \
                  make build

                FROM ubuntu:latest
                RUN \
                  apt-get update && \
                  DEBIAN_FRONTEND=noninteractive apt-get install -y \
                    pandoc texlive-latex-base texlive-latex-extra texlive-xetex && \
                  rm -rf /var/lib/apt/lists/*
                WORKDIR /app
                COPY --from=builder /app/mealie-addons .
                ENTRYPOINT ["/app/mealie-addons"]
        environment:
            MA_LISTEN_INTERFACE: ":9000"
            MA_RETRIEVAL_LIMIT: "5"
            MA_TIMEOUT_SECS: "60"
            MA_STARTUP_GRACE_SECS: "30"
            # See readme for the meaning of this variable. It has to be adjusted
            # or links in the exported documents that point back to the original
            # mealie instance will not work.
            MEALIE_BASE_URL: "<TODO>"
            # Mealie-addons has to be able to reach mealie via this URL. Finding
            # the correct value might be complicated depending on how Unraid
            # handles networking.
            MEALIE_RETRIEVAL_URL: "<TODO>"
            MEALIE_TOKEN: "/run/secrets/MEALIE_TOKEN"
            GIN_MODE: release
        secrets:
            - MEALIE_TOKEN

secrets:
    MEALIE_TOKEN:
        # This is the file containing the token used to access mealie. The path
        # is relative to the location of this file. Depending on how Unraid
        # handles secrets, this bit might have to be adjusted.
        file: mealie_token.txt
```

The crux is the `MEALIE_RETRIEVAL_URL`. When deploying both via the same compose file, we can simply use the service name `mealie` to access it thanks to the DNS records set up by docker compose.

Does this help?

**Comment by diedrichg** [comment]
Some info:  Unraid natively handles custom docker images by providing a template layout to input your docker commands as seen here:

![Image](https://github.com/user-attachments/assets/4b80199f-82d8-4d36-8300-a990f127c40f)

To do something like the Build section of the compose file I'm assuming the image needs to be built straight from a docker compose file. There is a plugin you can install from the Unraid app store called "docker compose manager". This then adds a section at the bottom of the Docker screen where you can add custom stacks using docker compose files. 

![Image](https://github.com/user-attachments/assets/a1391d6d-3b7c-4dca-b44b-bb6db92ac966)

I believe the image install process is choking on the "build" section of the compose file?  Is this the result of not  having a "volumes" variable in the compose file? Here is the output:



> [+] Building 1.8s (10/12)                                                                                                                       docker:default
 => [mealie-addons internal] load build definition from Dockerfile                                                                                        0.0s
 => => transferring dockerfile: 584B                                                                                                                      0.0s
 => [mealie-addons internal] load metadata for docker.io/library/ubuntu:latest                                                                            0.7s
 => [mealie-addons internal] load metadata for docker.io/library/golang:1.23-bookworm                                                                     0.8s
 => [mealie-addons internal] load .dockerignore                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                           0.0s
 => [mealie-addons builder 1/4] FROM docker.io/library/golang:1.23-bookworm@sha256:441f59f8a2104b99320e1f5aaf59a81baabbc36c81f4e792d5715ef09dd29355       0.0s
 => CACHED [mealie-addons stage-1 1/4] FROM docker.io/library/ubuntu:latest@sha256:72297848456d5d37d1262630108ab308d3e9ec7ed1c3286a32fe09856619a782       0.0s
 => CACHED [mealie-addons builder 2/4] RUN   apt-get update &&   DEBIAN_FRONTEND=noninteractive apt-get install -y make git                               0.0s
 => CACHED [mealie-addons builder 3/4] WORKDIR /app                                                                                                       0.0s
 => CANCELED [mealie-addons stage-1 2/4] RUN   apt-get update &&   DEBIAN_FRONTEND=noninteractive apt-get install -y     pandoc texlive-latex-base texli  1.0s
 => ERROR [mealie-addons builder 4/4] RUN   git clone https://github.com/razziel89/mealie-addons . &&   git checkout "${MA_VERSION}" &&   make build      0.9s                                                                                                                                        
 => [mealie-addons builder 4/4] RUN   git clone https://github.com/razziel89/mealie-addons . &&   git checkout "${MA_VERSION}" &&   make build:                 
0.351 Cloning into '.'...                                                                                                                                      
0.908 fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths                                                        
=>failed to solve: process "/bin/sh -c git clone https://github.com/razziel89/mealie-addons . &&   git checkout \"${MA_VERSION}\" &&   make build" did not complete successfully: exit code: 128

**Comment by razziel89** [comment]
Thanks for the details and the build log. It seems as if the build argument `MA_VERSION` is not correctly interpreted by the docker-compose plugin. My suggestion at a fix would be to replace the part that is `"$${MA_VERSION}"` by the version string `0.1.0` itself. That should work.

That being said, though, I though it might be easiest to provide a docker image that people can just use instead of having to build it themselves. I've just managed to upload the image. It is available at `ghcr.io/razziel89/mealie-addons:latest`. Due to size constraints of the GitHub Container Registry, I'll only be able to upload a single image, which means it will be overwritten with every new release.

Could you please have another try, either with docker-compose and building the image yourself, or with the pre-built image?

**Comment by diedrichg** [comment]
Sorry for the delay; busy weekend!

Using the 0.1.0 substitution worked as expected properly building the container. Running the stand-alone compose file from the front page of this project errored out.

**My usage:**

> ---
> services:
>     mealie-addons:
>         image: ghcr.io/razziel89/mealie-addons:latest
>         container_name: mealie-addons
>         restart: always
>         ports:
>             - "9926:9000"
>         environment:
>             MA_LISTEN_INTERFACE: ":9000"
>             MA_RETRIEVAL_LIMIT: "5"
>             MA_TIMEOUT_SECS: "60"
>             MA_STARTUP_GRACE_SECS: "30"
>             MEALIE_BASE_URL: "http://10.83.20.11:9000"
>             MEALIE_RETRIEVAL_URL: "http://10.83.20.11:9000"
>             MEALIE_TOKEN: "/run/secrets/MEALIE_TOKEN"
>             GIN_MODE: release
>             PANDOC_FLAGS: |-
>                 --epub-title-page
>                 false
>         secrets:
>             - MEALIE_TOKEN
> 
> secrets:
>     MEALIE_TOKEN:
>         # This is the file containing the token used to access mealie. The path
>         # is relative to the location of this file.
>         file: mealie_token.txt

**Error message:**

> Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /boot/config/plugins/compose.manager/projects/new/mealie_token.txt

**Comment by razziel89** [comment]
Thanks. How did you provide your mealie token to mealie-addons? Where is the file located that contains the token, relative to the location of the compose file?

Sorry for my brevity, I'm only on mobile right now.

**Comment by razziel89** [comment]
Replying in more detail.  The error message indicates that the system wants to retrieve the mealie token from a file here

```
/boot/config/plugins/compose.manager/projects/new/mealie_token.txt
```

but cannot find it. I'm not sure how unraid's compose plugin handles secrets. Would it be possible to create this file and put your mealie token in it? If not, you can always put the token directly in the compose file. Taking the stand-alone compose file from the main page as an example, you can do so by replacing these lines in the compose file

```
            MEALIE_TOKEN: "/run/secrets/MEALIE_TOKEN"
            GIN_MODE: release
            PANDOC_FLAGS: |-
                --epub-title-page
                false
        secrets:
            - MEALIE_TOKEN

secrets:
    MEALIE_TOKEN:
        # This is the file containing the token used to access mealie. The path
        # is relative to the location of this file.
        file: mealie_token.txt
```

by this, making sure to put your actual token where `<TOKEN>` is

```
            MEALIE_TOKEN: "<TOKEN>"
            GIN_MODE: release
            PANDOC_FLAGS: |-
                --epub-title-page
                false
```

Does this work?

**Comment by diedrichg** [comment]
> How did you provide your mealie token to mealie-addons? Where is the file located that contains the token, relative to the location of the compose file?

I didn't realize that the API token was a strict requirement (makes sense now though).  I pointed the Compose File /secrets>file/ to the persistent data location of my Mealie instance where I have the mealie_token.txt stored. **_Success_**, mealie-addons is up and running. Now to read up on how to use/access the output files!

![Image](https://github.com/user-attachments/assets/174ba577-9f4c-4472-907b-bbc8c45e682d)

I plan to eventually follow-up on this text chain with instructions/screenshots of setting it up as a standard Docker container in Unraid's native UI. Thank you for your patience and help! I can't wait to publish my cookbooks, I wanted to send them out as Christmas presents this past holiday.

**Comment by diedrichg** [comment]
COOL! I am able to get the html version! http://*hostIP*:9926/book/html 
The pdf version errors out and does not produce a file. epub and markdown download just fine

PDF link:
![Image](https://github.com/user-attachments/assets/66d9bba8-d5bd-49c6-9f52-9639a1d1dfb9)

**Comment by razziel89** [comment]
Only on mobile right now so staying brief. 

Yeah, the docs are not too detailed when it comes to the token. That'll have to be amended.

Thanks a lot to you for your patience and for sticking with it despite the initial hiccups! I'm really looking forward to seeing that guide you mentioned. I think it can be very helpful for a lot of people. Would you mind if we were to add it to this repo?

Regarding the PDF error: do you see any output in the server logs on your unraid that could explain the problem? My recommendation would be to search for pandoc in the logs. It should be executed twice. If HTML works, then the second call will be causing a problem. The string `--to pdf` should be there, too. I suspect the problem could be related to the embedded images.

**Comment by diedrichg** [comment]
Just letting you know which methods work... 
1. Using the stand-alone compose file 'secrets: - MEALIE_TOKEN' I'm able to put the absolute path to the mealie_token.txt file that resides within my mealie persistent data. (/mnt/cache/appdata/mealie/mealie_token.txt)  - this method works.
2. Using the shortened version MEALIE_TOKEN: "<TOKEN>"  - this method also works just fine.
3. Unraid native interface:  https://github.com/razziel89/mealie-addons/issues/7

Here is my functioning compose file (note that I added the network_mode so that it was on the same docker network as Mealie):
```
services:
    mealie-addons:
        image: ghcr.io/razziel89/mealie-addons:latest
        network_mode: bridge
        container_name: mealie-addons
        restart: always
        ports:
            - "9926:9000"
        environment:
            MA_LISTEN_INTERFACE: ":9000"
            MA_RETRIEVAL_LIMIT: "5"
            MA_TIMEOUT_SECS: "60"
            MA_STARTUP_GRACE_SECS: "30"
            MEALIE_BASE_URL: "http://10.83.20.11:9000"
            MEALIE_RETRIEVAL_URL: "http://10.83.20.11:9000"
            MEALIE_TOKEN: "sUp3rCekR3TtAPInUm83RR"
            GIN_MODE: release
            PANDOC_FLAGS: |-
                --epub-title-page
                false
``` 

PDF error:
```
2025/02/12 21:50:38 retrieved 295 recipes for application/pdf
2025/02/12 21:50:38 there are 26 tags and 12 categories overall
2025/02/12 21:50:38 running pandoc with args: --standalone --pdf-engine=xelatex --variable=geometry:margin=2cm --epub-title-page false --from=markdown --to=html --output=-
2025/02/12 21:50:41 running pandoc with args: --standalone --pdf-engine=xelatex --variable=geometry:margin=2cm --epub-title-page false --from=markdown --to=html --output=- --from=html --to pdf
2025/02/12 21:50:43 unexpected error exit status 1
[GIN] 2025/02/12 - 21:50:43 | 500 | 13.364456411s |     10.83.20.87 | GET      "/book/pdf"
``` 

Yes, I will definitely contribute to your project with the Unraid steps  :)
